language: scala

scala:
- 2.12.10

jdk:
- oraclejdk8

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_f0942b579a2f_key -iv $encrypted_f0942b579a2f_iv -in secring.gpg.enc
    -out secring.gpg -d;
  fi

script:
- sbt test

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sbt compile publishSigned;
  fi
